<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array reshaping
 1. reshape()
 2. flatten() -> create copy
 3. ravel() - > return original
 4. transpose -> using T

In [ ]:
# Reshape array
import numpy as np
arr = np.arange(12)
up_arr = arr.reshape(3,4) # 3 -> rows | 4 -> coloums
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# example
import numpy as np
arr = np.arange(16).reshape(2,4,2) # 2 -> array | 4 -> rows in both | 2 -> coloums in both
print(arr)



[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [ ]:
# flatten -> create a copy than works
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
up_arr = arr.flatten()
print(up_arr)
print(arr)

# exanple for 3d
arr1 = np.arange(16).reshape(2,4,2)
print(arr1)
up_arr1 = arr1.flatten()
up_arr1[0] = 100
print(up_arr1)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [ ]:
# Ravel for 2d -> works on original array
import numpy as np
arr = np.arange(14).reshape(2,7)
print(arr)
up_arr = arr.ravel()
print(up_arr)
print(arr)

# ravel for 3d
arr1 = np.arange(32).reshape(2,4,4)
print(arr1)
up_arr1 = arr1.ravel()
up_arr1[0] = 100
print(up_arr1)
print(arr1)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
[[[100   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [ 12  13  14  15]]

 [[ 16  17  18  19]
  [ 20  21  22  23]
  [ 24  25  26  27]
  [ 28  29  30  31]]]


In [ ]:
# Transpose -> convert row into coloum

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)
up_arr = arr.T
print(up_arr)
arr1 = np.arange(16)
print(arr1)
up_arr = arr1.reshape(4,4).T
print(up_arr)

# for 3d
arr2 = np.arange(32).reshape(2,4,4)
print(arr2)
up_arr2 = arr2.T
print(up_arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 0 16]
  [ 4 20]
  [ 8 24]
  [12 28]]

 [[ 1 17]
  [ 5 21]
  [ 9 25]
  [13 29]]

 [[ 2 18]
  [ 6 22]
  [10 26]
  [14 30]]

 [[ 3 19]
  [ 7 23]
  [11 27]
  [15 31]]]


# Slicing for 1d 2d 3d

In [ ]:
# for 1d
import numpy as np
arr = np.arange(10)
print(arr[3:6])
print(arr[:6])
print(arr[3:])
print(arr[3:6:2])
print(arr)

[3 4 5]
[0 1 2 3 4 5]
[3 4 5 6 7 8 9]
[3 5]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# for 2d
import numpy as np
arr = np.arange(16).reshape(2,8)
print(arr)
up_arr = arr[:,-1]
print(up_arr)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[ 7 15]


In [ ]:
# for 3d
import numpy as np
arr = np.arange(24).reshape(3,4,2)
print(arr)
up_arr = arr[::2,::3,::]
print(arr[0::2,0::3,0::1][:,[0,1],[0,1]])
# print(up_arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[ 0  7]
 [16 23]]


Looping using Numpy
  1. while loop
  2. for loop

In [ ]:
# while loop
# for 1d
import numpy as np
arr = np.arange(12)
i = 0
while i< len(arr):
  print(arr[i], end=" ")
  i += 1


# for 2d
import numpy as np
arr = np.arange(16).reshape(4,4)
i = 0
while i< len(arr):
  j = 0
  while j< len(arr[i]):
    print(arr[i][j], end=" ")
    j += 1

  print("\n")
  i += 1




0 1 2 3 

4 5 6 7 

8 9 10 11 

12 13 14 15 



In [ ]:
# for loop
# for 1d
import numpy as np
arr = np.arange(12)
for i in range(12):
  print(arr[i], end="  ")

arr1 = np.arange(16).reshape(2,8)
for i in range(len(arr1)):
  for j in range(len(arr1[i])):
    print(arr1[i][j], end=" ")
  print("\n")

0 1 2 3 4 5 6 7 

8 9 10 11 12 13 14 15 



In [ ]:
import numpy as np
arr = np.zeros(16).reshape(4,4)
for i in range(len(arr)):
  for j in range(len(arr[i])):
    if i == j:
      arr[i][j] = 1
    print(arr[i][j], end=" ")
  print("\n")

1.0 0.0 0.0 0.0 

0.0 1.0 0.0 0.0 

0.0 0.0 1.0 0.0 

0.0 0.0 0.0 1.0 

