<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Creating array from list**

In [ ]:
#1d list
l = [1,2,3]
print(l)

#1d array
import numpy as np
arr = np.array(l)
print(arr)

#2d list

l = [[1,2,3],[4,5,6]]
print(l)
l[1][0]= 100
print(l)

#2d array
n = np.array([[1,2,3],[4,5,6]])
print(n)
print(n[0]) #1st row -> [1,2,3]



[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [100, 5, 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3]


# **list vs array**
    1. Multiply
    2. Comparasion
    3. Zeros
    4. Ones
    5. Full
    6. Random
    7. Arrange

In [ ]:
# list
l = [1,2,3]
lm = l*2
print(lm)

#array
import numpy as np
arr = np.array(l)
arrm = arr*2
print(arrm)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
#comparasion
#  array takes less time comparasion by list
#list
import time
start = time.time()
l = [i*500 for i in range(1000000)]
print("list output:" , time.time() - start)


#array
import numpy as np
start = time.time()
arr = np.arange(1000000)*500
print("array output:" , time.time() - start)


list output: 0.07245302200317383
array output: 0.003718137741088867


In [ ]:
# Zeros array
import numpy as np
arr = np.zeros(5)
print(arr)
# 2d
arr = np.zeros((2,5))
print(arr)


[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# ones array 1d
import numpy as np
arr = np.ones(5)
print(arr)
#ones array 2d
arr = np.ones((2,5))
print(arr)


[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Question
# use of zeros increase by 10
# use of ones increase 5
import numpy as np
arr = np.zeros((2,5))
print(arr+10)
arr = np.ones((2,5))
print(arr*5)


[[20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
# full for 1d
import numpy as np
arr = np.full(5,8)
print(arr)
# full for 2d
arr = np.full((2,6),7)
print(arr)

[8 8 8 8 8]
[[7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [ ]:
# Question
# by the help of zeros -> 2d -> 6
# by the help of full -> 2d -> 1
import numpy as np
arr = np.zeros((2,6))+6
print(arr)
arr = np.full((2,6),1)
print(arr)

[[6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
# Random
import random
import numpy as np
arr = np.random.random((2,6))
print(arr)


[[0.64553609 0.15324825 0.88190757 0.76409724 0.47028011 0.93852299]
 [0.37831174 0.74577249 0.4390272  0.69557543 0.39646648 0.45959232]]


In [ ]:
# arange for 1d
import numpy as np
arr = np.arange(5)
print(arr)
# arange for 2d
arr = np.arange(20).reshape(4,5)
print(arr)

[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# vector , matrix , tensor
  1. 1d -> vector
  2. 2d -> matrix
  3. 3d -> tensor

In [5]:
# vector -> 1d list
# vector -> 1d array
import numpy as np
n = [1,2,3,4]
print(n)

arr = np.array(n)
print(arr)

# matrix

n = [[1,2,3],[4,5,6]]
print(n)

arr = np.array(n)
print(arr)

# tensor

# n = [[[1,2],[3,4],[[5,6],[7,8]]]]
# print(n)
# a = np.array(n)
# print(n)
#

[1, 2, 3, 4]
[1 2 3 4]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# array
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
print("shape:" , arr.shape)
print("shape:" , np.shape(arr))
print("dimension:", np.ndim(arr))
print("size:" , np.size(arr))
print("datatype:", arr.dtype)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)
shape: (3, 4)
dimension: 2
size: 12
datatype: int64


array reshaping
