<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sorting**
   1. sort for 1d
   2. sort for 2d using (use axis=0-> cols) & (axis=1-> rows)

In [ ]:
# sort()
import numpy as np
arr = np.array([10,40,30,20,90,5,1])
print(arr)
print(np.sort(arr))

[10 40 30 20 90  5  1]
[ 1  5 10 20 30 40 90]


In [ ]:
# for 2d
import numpy as np
arr = np.array([[30,50,60,40,40,50],[1,4,6,3,7,5]])
print(arr)
print(np.sort(arr)) # by default row wise
print(np.sort(arr,axis=0)) # column wise
print(np.sort(arr,axis=1)) # row wise

[[30 50 60 40 40 50]
 [ 1  4  6  3  7  5]]
[[30 40 40 50 50 60]
 [ 1  3  4  5  6  7]]
[[ 1  4  6  3  7  5]
 [30 50 60 40 40 50]]
[[30 40 40 50 50 60]
 [ 1  3  4  5  6  7]]


In [ ]:
# Qs.
import numpy as np
arr = np.array([[32,56,31,77,56,23],[23,45,34,55,63,49]])
print(arr)
up_arr = np.sort(arr,axis=1)
print(up_arr)
desc_arr = np.sort(up_arr,axis=1)[::-1]
print(desc_arr)

[[32 56 31 77 56 23]
 [23 45 34 55 63 49]]
[[23 31 32 56 56 77]
 [23 34 45 49 55 63]]
[[23 34 45 49 55 63]
 [23 31 32 56 56 77]]


# **Filter**
   1. array[Expression]
   2. array[array>2] || filter with mask

In [ ]:
# filter
import numpy as np
arr = np.array([41,42,44,45,4,5,60])
print(arr)
arr_f = arr[arr>40]
print(arr_f)

[41 42 44 45  4  5 60]
[41 42 44 45 60]


In [ ]:
# Example
import numpy as np
arr = np.array([1,4,2,6])
print(arr)
arr_f = arr[arr<5]
print(arr_f)


[1 4 2 6]
[1 4 2]


# Fancy **indexing**

In [ ]:
import numpy as np
arr = np.array([2,4,2,6,4,7])
print(arr)
arr_f = arr[[1,2,3]]
print(arr_f)

[2 4 2 6 4 7]
[4 2 6]


In [ ]:
# for 2d
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0,3])
arr_f = arr[[0,1,2],[1,2,3]]
print(arr_f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4
[ 2  7 12]


# **where()**

In [ ]:
# np.where()
import numpy as np
# 1d
arr = np.array([10,30,4,2,6,80,40,9])
print(arr)
arr_f = np.where(arr>20,"True","false")
print(arr_f)
arr_multi = np.where(arr>20,arr+2,arr-2)
print(arr_multi)

[10 30  4  2  6 80 40  9]
['false' 'True' 'false' 'false' 'false' 'True' 'True' 'false']
[ 8 32  2  0  4 82 42  7]


In [ ]:
# example
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

arr_a = np.where((arr > 10) & (arr < 25), "hello", "bye")

print(arr_a)

['bye' 'bye' 'hello' 'hello' 'bye']


Adding and Removing Data

1. np.concatenate((arr1,arr2))
2. np.vstack((original,new_row)) add new row
3. np.hstack((original,new_col)) add new col
4. np.delete(arr,index_no) delete element by index number

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1)
print(arr2)
a = arr1+arr2
print(a)
arr_f = np.concatenate((arr1,arr2))
print(arr_f)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[1 2 3 4 5 6 7 8]


In [ ]:
# for 2d
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1)
print(arr2)
arr_f = np.concatenate((arr1,arr2),axis=0)
print(arr_f)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


In [ ]:
# for 2d
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[9,10,11,12],[13,14,15,16]])
print(arr1)
print(arr2)
arr_f = np.concatenate((arr1,arr2))
print(arr_f)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# **Statistical Functions**

  1. np.sum(a) -> Sum of all elements

   2. np.mean(a) -> Average = Sum of elements / Number of elements

  3. np.median(a) -> Middle value after sorting

4. np.min(a) -> Smallest value in array

5.  np.max(a) -> Largest value in array

6.  np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length

7.  np.std(a) -> Standard Deviation = √Variance -> Measures spread of data

8.  np.prod(a) -> Multiplication of all elements

9. np.cumsum(a) -> Cumulative (running) sum

10. np.cumprod(a) -> Cumulative (running) product

11. np.argmin(a) -> Index position of minimum value

12. np.argmax(a) -> Index position of maximum value

13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)

14. np.unique(a) -> Returns unique values only -> Removes duplicates

15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median

16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%

17. np.ptp(a) -> Range = Max - Min

18. np.any(a) -> True if at least one value is True

In [ ]:
# sum
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

# mean
print(np.mean(arr))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

# median
print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

# min
print(np.min(arr))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))

# max
print(np.max(arr))
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))



21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
[2.5 3.5 4.5]
[2. 5.]
1
[1 2 3]
[1 4]
6
[4 5 6]
[3 6]
