<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data preprocessing**

In [ ]:
# handle missing values
import pandas as pd
import numpy as np
data = {
"colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
# print(df)

# handle null values
df.dropna(inplace=True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [ ]:
# label encoding
from sklearn.preprocessing import LabelEncoder

# method 1
le = LabelEncoder()
df['colors_encoder1'] = le.fit_transform(df['colors'])

# method 2
df['colors_encoder2'] = LabelEncoder().fit_transform(df['colors'])
# print(df)

# method 3
import sklearn
df['colors_encoder3'] = sklearn.preprocessing.LabelEncoder().fit_transform(df['colors'])
print(df)

   colors  colors_encoder1  colors_encoder2  colors_encoder3
0     red                3                3                3
1   green                1                1                1
2    blue                0                0                0
3  orange                2                2                2
4   green                1                1                1
5    blue                0                0                0


In [ ]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder1' in df.keys():
   df.drop(df[['colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
df_encoded = encoder.fit_transform(df[['colors']])
print(df_encoded)

# by help of sklearn
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['colors']])
print(encoded.toarray())


# one hot encoding by help of pandas
# df_encoder = pd.get_dummies(df,coloums=['colors'])
# print(df_encoder)


   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors_blue  colors_green  colors_orange  colors_red
0          0.0           0.0            0.0         1.0
1          0.0           1.0            0.0         0.0
2          1.0           0.0            0.0         0.0
3          0.0           0.0            1.0         0.0
4          0.0           1.0            0.0         0.0
5          1.0           0.0            0.0         0.0
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [ ]:
# Combination of -> H.m.v | L.E | O.H.E

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
data = {
    "age":[10,20,np.nan,26,30],
    "gender":['male','female','others','male',np.nan],
    "name":['dheeraj','kavi','sapu','yash','hello']
}

df = pd.DataFrame(data)
print(df)

# Handle missing values
df['age'] = df['age'].fillna(df['age'].mean())
df.dropna(subset=['gender'],inplace=True)
print(df)

#label Encoding
le= LabelEncoder()
df['gender']= le.fit_transform(df['gender'])
print(df)

# one hot encoder
oe= OneHotEncoder()
oe_e= oe.fit_transform(df[['gender']]).toarray()
print(oe_e)

    age  gender     name
0  10.0    male  dheeraj
1  20.0  female     kavi
2   NaN  others     sapu
3  26.0    male     yash
4  30.0     NaN    hello
    age  gender     name
0  10.0    male  dheeraj
1  20.0  female     kavi
2  21.5  others     sapu
3  26.0    male     yash
    age  gender     name
0  10.0       1  dheeraj
1  20.0       0     kavi
2  21.5       2     sapu
3  26.0       1     yash
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
