<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy
# import numpy as Abhishek
# from numpy import arange
# from numpy import *
n = numpy.arange(11)
print(type(n))
print(n[0])
print(n[5])
print(n)


# example (2d array)
n = numpy.arange(12)
d = n.reshape(3,4)  # 3 rows 4 coloum
print(type(d))
print(d)

n = numpy.arange(12).reshape(3,4)
print(n)

n = numpy.arange(12)
a = n.reshape(4,3)
print(type(a))
print(a)
print(a[0:4,2:3])
print(a[1,2:3])
print(a[1:3,1])

<class 'numpy.ndarray'>
0
5
[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[5]
[4 7]


In [ ]:
# example


In [ ]:
# # # # a = 10
# # # # b = 20
# # # # print(a,b)

# # # # a, b = b, a

# # # # print(a, b)  # 20 10
# # # pairs = [(1, 'a'), (2, 'b'), (3, 'c')]
# #               # global

# # def increment():
# #   count += 1
# #   print(count)

# # increment()

# #            # 1.
# squares = [x**2 for x in range(10)]
# print (squares)
nums = [4, 2, 7, 1, 9]
print(min(nums))               # 1
print(max(nums))               # 9
print(sum(nums))               # 23
print(sorted(nums))            # [1,2,4,7,9] — new list
print(list(reversed(nums)))    # reversed copy
print(nums.index(7))           # 2  (index of value 7)
print(nums.count(4))

1
9
23
[1, 2, 4, 7, 9]
[9, 1, 7, 2, 4]
2
1
